spring.application.name=propertymanagement


# H2 Database
# Allow access to the H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Database configuration
spring.datasource.url=jdbc:h2:file:./data/propertydb;
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
# Format SQL output for better readability
spring.jpa.properties.hibernate.format_sql=true

